// Generated by search17_prepare.py; pins the order-17 dataset.
#pragma once
namespace fan_cli {
inline constexpr const char* EXPECTED_CATALOG_FNV = "c85356b27cb99c84";
inline constexpr const char* EXPECTED_LEFT_FNV = "b9004989289e8545";
inline constexpr const char* EXPECTED_RIGHT_FNV = "d09ff1e67238a810";
inline constexpr const char* EXPECTED_DATASET = "e38c0723b6a3be74";
inline constexpr unsigned long long EXPECTED_PAIRS = 88294674ULL;
inline constexpr unsigned EXPECTED_LEFT_PROFILES = 6860U;
inline constexpr unsigned EXPECTED_RIGHT_PROFILES = 60041U;
}
